name: GetPetOwner
version: 1.0
description: Get the owner of a pet!
authors:
  - 1am3r
  - noroom
website: http://1am3r.github.com/GetPetOwner/

main: com.github._1am3r.GetPetOwner.GetPetOwner

permissions:
  getpetowner.getowner:
    description: Allows a player to get the name of the owner of a pet
    default: true
    