name: GetWolfOwner
version: 1.4
description: Get the owner of a wolf!
authors:
  - 1am3r
  - noroom
website: http://1am3r.github.com/GetWolfOwner/

main: com.github._1am3r.GetWolfOwner.GetWolfOwner

permissions:
  getwolfowner.getowner:
    description: Allows a player to get the name of the owner of a wolf
    default: true
    